### PR TITLE
Update lorem_ipsum.yaml

### PR DESCRIPTION
**Pull request by ptitzler**
This PR relates to https://github.com/CODAIT/exchange-metadata-converter/issues/4
- Adds a child property `columns` that can optionally provide data structure information for columnar data files

### CODE REVIEW

**Comment by ptitzler** [comment]
Need to decide on what the enum should look like for data types. Ideally the values should be programming language independent but if you want to go with Python ...
Not sure what is currently used in the glossary/previewer

**Review by edwardleardi — APPROVED** [review]
Not sure I know what you mean by enum. Is this a datatype that datasets can use?

**Comment by ptitzler** [comment]
The property value in `type` defines the column data type, e.g. string. We need to figure out what valid values are to avoid inconsistencies. For example, do we use `str` or `string` or `String` to identify a string?
The enumeration would define valid type names, e.g. ['str','bool,...] to achieve consistency

**Comment by edwardleardi** [comment]
Ah, I see, thanks. We haven't added column types to our data previews yet, but that was planned. My guess is that we'll wait until we integrate a converter from this repo to generate future data previews when including column type info. 

I would probably agree that programming language independent format is fine here since it seems Python scripts will not be the only ones pulling metadata from here. The data previews actually use a JS script to generate. Is there a universal standard that gets used for non-programming language specific data types like in this scenario?

From a Python/Pandas perspective I can think of these data types that we may want:
* Integer (do we want to distinguish by bits?)
* Float
* String
* Bool
* Datetime?
* Timedelta?
* Categorical?
* Mixed?
* None?

@xuhdev @djalova do you have an opinion on this?

**Comment by xuhdev** [comment]
We can proceed with basic ones for a start, and expand when we encounter some unusual datatypes. I would start from the first five and expand as we need.

**Pull request merged**
